export * from 'io-ts/lib/index.js';
export type { ToIoType, ToTsType } from './misc.js';
export { PromiseTypeError, _brand, decode, isDerivedFrom, isExtensionOf, render} from './misc.js';
export * from './ternary.js';
export * from './extensionRegistry.js';
export { ClssType, Implementation, clss, extendClss } from './types/clss.js';
export type { Parameter } from './types/function.js';
export { FunctionType, fn, nullFunction, stripNullFunctions } from './types/function.js';
export { intersectionSourceDefaultHandler, intersectionTargetDefaultHandler } from './types/intersection.js';
export type { Nullable } from './types/nullable.js';
export { NullableType, nullable } from './types/nullable.js';
export { PromiseType, promise } from './types/promise.js';
export { unionSourceDefaultHandler, unionTargetDefaultHandler } from './types/union.js';

import { initAny } from './types/any.js';
import { initAnyArray } from './types/anyarray.js';
import { initAnyDictionary } from './types/anydictionary.js';
import { initArray } from './types/array.js';
import { initBigInt } from './types/bigint.js';
import { initBoolean } from './types/boolean.js';
import { initClss } from './types/clss.js';
import { initDictionary } from './types/dictionary.js';
import { initExact } from './types/exact.js';
import { initFunction } from './types/function.js';
import { initInterface } from './types/interface.js';
import { initIntersection } from './types/intersection.js';
import { initKeyof } from './types/keyof.js';
import { initLiteral } from './types/literal.js';
import { initNever } from './types/never.js';
import { initNull } from './types/null.js';
import { initNullable } from './types/nullable.js';
import { initNumber } from './types/number.js';
import { initPartial } from './types/partial.js';
import { initPromise } from './types/promise.js';
import { initReadonly } from './types/readonly.js';
import { initReadonlyArray } from './types/readonlyarray.js';
import { initRecursive } from './types/recursive.js';
import { initRefinement } from './types/refinement.js';
import { initString } from './types/string.js';
import { initTuple } from './types/tuple.js';
import { initUndefined } from './types/undefined.js';
import { initUnion } from './types/union.js';
import { initUnknown } from './types/unknown.js';
import { initVoid } from './types/void.js';

initAny();
initAnyArray();
initAnyDictionary();
initArray();
initBigInt();
initBoolean();
initClss();
initDictionary();
initExact();
initFunction();
initIntersection();
initInterface();
initKeyof();
initLiteral();
initNever();
initNull();
initNullable();
initNumber();
initPartial();
initPromise();
initReadonly();
initReadonlyArray();
initRecursive();
initRefinement();
initString();
initTuple();
initUndefined();
initUnion();
initUnknown();
initVoid();
